    import React from 'react';
    import ReactDOM from 'react-dom/client';
    import './index.css'; // Your main CSS file (e.g., generated by Tailwind's build)
    import App from './App'; // Import your main App component
    import { BrowserRouter } from 'react-router-dom'; // <--- IMPORTANT: Import BrowserRouter

    // Create a root for React 18+ (standard setup)
    const root = ReactDOM.createRoot(document.getElementById('root'));

    // Render the App component wrapped in BrowserRouter.
    // This makes routing available throughout your application.
    root.render(
      <React.StrictMode>
        <BrowserRouter> {/* All components inside BrowserRouter can use React Router's features */}
          <App />
        </BrowserRouter>
      </React.StrictMode>
    );
    